substitutions:
  name: "smart-air-freshener"
  project_name: "The_Printing_Pilot.Smart_Air_Freshener"
  project_version: "1.0.1"
  CCW: '3'   #To change motor direction chnage this to 3
  CW: '4'    #To change motor direction chnage this to 4

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
   name: "${project_name}"
   version: "${project_version}"
  min_version: 2025.5.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: ""

web_server:
  port: 80

improv_serial:

captive_portal:
  
switch:
  - platform: gpio
    pin: ${CW}
    inverted: false
    name: "DontUse1"
    id: DontUse1
    internal: True

  - platform: gpio
    pin: ${CCW}
    inverted: false
    name: "DontUse2"
    id: DontUse2
    internal: True

  - platform: template
    name: "Refil"
    id: refil
    optimistic: True
    turn_on_action:
      - number.set:
          id: spray_count
          value: 0
      - delay: 350ms
      - switch.turn_off: refil
        
  - platform: template
    name: "Spray"
    id: Spray
    optimistic: True
    on_turn_on:
      - switch.turn_on: DontUse1
      - switch.turn_off: DontUse2
      - delay: 350ms
      - switch.turn_on: DontUse1
      - switch.turn_on: DontUse2
      - delay: 500ms
      - switch.turn_on: DontUse2
      - switch.turn_off: DontUse1
      - delay: 350ms
      - switch.turn_off: DontUse2
      - switch.turn_off: DontUse1    
      - switch.turn_off: Spray
      - number.increment:
          id: spray_count

select:
  - platform: template
    name: "mode"
    id: run_mode
    options:
      - "AUTO"
      - "MANUAL"
    initial_option: "AUTO"
    optimistic: true

binary_sensor:
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true    
    name: "Physical Button"
    on_multi_click:
    - timing:
        - ON for at most 2s
        - OFF for at most 2s
        - ON for at most 2s
        - OFF for at least 0.2s
      then:
      - logger.log: "Double Clicked"
      - delay: 5s
      - switch.turn_on: Spray
    - timing:
        - ON for at most 2s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"    
        - delay: 2s
        - switch.turn_on: Spray 

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: ic_temp

number:
  - platform: template
    id: spray_count
    name: Spray Count
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 1000
    step: 1